formatter: "markdown table"
version: ""
header-from: "docs/header.md"
footer-from: "docs/footer.md"

recursive:
  enabled: false

content: |
  {{ .Header }}

  # Example

  ```hcl
  {{ include "docs/examples/main.tf" }}
  ```

  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
